name: Markdown Linting Action
description: GitHub Action to run markdown linter
author: avto-dev

inputs: # <https://git.io/JvkYF#inputs>
  config:
    description: 'Configuration file (JSON, JSONC, or YAML). Place a custom configuration file (e.g., .markdownlint.yml) next to this file to enable loading of it.'
    required: false
  fix:
    description: 'Fix basic errors'
    required: false
    default: 'false'
  args: # do not change this name! reason: <https://git.io/Jvk8K> (usage as named action and docker image with same syntax)
    description: 'Files (globs) for a work or any additional arguments'
    required: true

runs: # <https://git.io/JvkYF#runs>
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.args }}

branding: # <https://git.io/JvkYF#branding>
  icon: file-text
  color: green
