# The file extension of this file needs to be `yaml`, because `yml` is not supported

customRules:
  # workaround for https://github.com/DavidAnson/markdownlint-cli2/issues/49
  - "/lint/changelog/changelog.js"
